package config

import (
	"encoding/json"
	"errors"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// AIProvider is one OpenAI-compatible backend the drafting worker may use.
// Providers form an ordered failover list (see AIProviders): the worker tries
// the first and falls back to the next on error. APIKey is the resolved secret
// (already read from its referencing env var), never logged.
type AIProvider struct {
	Name     string // short label for logs (e.g. "local", "gemini")
	Endpoint string // API root, e.g. "http://127.0.0.1:11434/v1"
	Model    string // model name passed to the endpoint
	APIKey   string // bearer token; empty for local runtimes like Ollama
}

type Config struct {
	ListenAddr  string
	DatabaseURL string
	LogLevel    slog.Level

	// PublicBaseURL is the absolute origin the browser sees (e.g.
	// "https://mindful.example.org"). Required only when at least one OAuth
	// provider is configured, because callback URLs are derived from it.
	PublicBaseURL string

	// SignupEnabled gates new-account creation via the email+password
	// signup form. When false, the form is replaced by a "signups closed"
	// page that still offers OAuth/SSO. OAuth callbacks continue to create
	// users — SSO is the intended fallback for closed instances.
	SignupEnabled bool

	// AdminUsers is the list of usernames that get the 'admin' role
	// granted on startup, reconciled idempotently. The intended use is
	// bootstrapping the first admin on a fresh install; subsequent role
	// changes happen through the admin UI. Unknown usernames are logged
	// and skipped.
	AdminUsers []string

	// DataDir is the writable base directory for persistent state owned
	// by the service (currently just uploads, but the natural home for
	// any future on-disk caches or generated assets). On NixOS this is
	// the systemd StateDirectory, /var/lib/mindful-social.
	DataDir string

	// UploadDir stores user-uploaded files served from /uploads/*.
	// Defaults to $DATA_DIR/uploads; override UPLOAD_DIR to point
	// elsewhere (e.g. a mounted object-storage bucket).
	UploadDir string

	// NodeImageMaxUploadBytes is the raw request-body ceiling for node
	// image uploads, enforced via http.MaxBytesReader before decoding.
	NodeImageMaxUploadBytes int64

	// NodeImageMaxDimension caps the longest side (in pixels) of stored
	// node images. Anything larger is downscaled, preserving aspect ratio.
	NodeImageMaxDimension int

	// NodeImageBytesPerMegapixel is the per-megapixel byte budget the
	// JPEG re-encoder targets. With the default 512000 bytes (~500 KiB)
	// a 1920x1080 frame aims for ~1.06 MB before quality stepping kicks
	// in. GIFs bypass recompression to preserve animation.
	NodeImageBytesPerMegapixel int64

	// AudioDir stores Opus audio chunks generated by the TTS worker,
	// laid out as <AudioDir>/<node-id>/<chunk-index>.opus. Defaults to
	// $DATA_DIR/audio. Files are served from /audio/* through the same
	// gated handler pattern as /uploads.
	AudioDir string

	// TTSSidecarURL is the base URL of the Python Kokoro service that
	// performs synthesis. Empty disables TTS — node uploads still work
	// but no audio is enqueued. The default 127.0.0.1:8090 matches
	// tts/run.sh.
	TTSSidecarURL string

	// AIEndpointURL is the base URL of an OpenAI-compatible chat
	// completions API used to draft nodes from a prompt (e.g.
	// "http://127.0.0.1:11434/v1" for a local Ollama). Empty disables the
	// AI draft feature: the "Generate with AI" entry point is hidden and
	// the /nodes/generate routes 404. Anything that speaks the OpenAI
	// wire format works (Ollama, vLLM, llama.cpp, LM Studio, OpenRouter,
	// or a hosted provider).
	AIEndpointURL string

	// AIModel is the model name passed to the endpoint (e.g.
	// "llama3.1:8b"). Only consulted when AIEndpointURL is set.
	AIModel string

	// AIAPIKey is the bearer token for the endpoint. Optional — local
	// runtimes like Ollama ignore it; hosted providers require it. Keep it
	// out of the repo; supply via an environment file in production.
	AIAPIKey string

	// AIProviders is the ordered list of OpenAI-compatible backends the
	// drafting worker uses, tried first-to-last with automatic failover. It
	// is derived in Load from either AI_PROVIDERS (a JSON array) or, when
	// that is unset, the legacy AI_ENDPOINT_URL/AI_MODEL/AI_API_KEY trio
	// (a single "default" provider). Empty means AI drafting is disabled.
	// This is the single source the server consumes; the scalar AI* fields
	// above only feed the fallback path.
	AIProviders []AIProvider

	// SearxngURL is the base URL of a SearXNG metasearch instance used to
	// ground AI drafts in web search results (e.g. "http://127.0.0.1:8888").
	// Empty disables the "Search the web" option — URL-grounded drafting
	// (fetching user-supplied links) still works without it. Only consulted
	// when AIEndpointURL is also set.
	SearxngURL string

	// AIJobTimeout is the ABSOLUTE ceiling on one background drafting job end
	// to end (web fetches + model generation) — a backstop against a runaway
	// job, not the primary guard. Since generation streams, the real
	// stall-detection is AIStreamIdleTimeout below; a slow-but-progressing
	// model is never killed by this cap unless it genuinely runs this long.
	// Generous by design; tune via AI_JOB_TIMEOUT (e.g. "45m").
	AIJobTimeout time.Duration

	// AIStreamIdleTimeout is how long the model may produce NO output before
	// the streaming generation is treated as stalled and cancelled. The clock
	// resets on every token, so a model that keeps emitting text — however
	// slowly — keeps running; only a truly hung stream is killed. This is the
	// primary generation guard (AIJobTimeout is just the outer backstop).
	// Tunable via AI_STREAM_IDLE_TIMEOUT (e.g. "2m").
	AIStreamIdleTimeout time.Duration
}

// Load reads configuration from environment variables.
// DATABASE_URL is required; everything else has sensible defaults.
// The logger receives warnings for misconfigured values that get
// silently replaced with defaults (e.g. an unrecognised boolean), so a
// typo in production at least leaves a trace in the log stream.
func Load(logger *slog.Logger) (Config, error) {
	if logger == nil {
		logger = slog.Default()
	}
	dataDir := envOr("DATA_DIR", ".")
	cfg := Config{
		ListenAddr:                 envOr("LISTEN_ADDR", "127.0.0.1:8080"),
		DatabaseURL:                os.Getenv("DATABASE_URL"),
		LogLevel:                   envLogLevel(logger, "LOG_LEVEL", slog.LevelInfo),
		PublicBaseURL:              envOr("PUBLIC_BASE_URL", "http://127.0.0.1:8080"),
		SignupEnabled:              envBool(logger, "SIGNUP_ENABLED", true),
		AdminUsers:                 envList("ADMIN_USERS"),
		DataDir:                    dataDir,
		UploadDir:                  envOr("UPLOAD_DIR", filepath.Join(dataDir, "uploads")),
		NodeImageMaxUploadBytes:    envInt64(logger, "NODE_IMAGE_MAX_UPLOAD_BYTES", 8<<20),
		NodeImageMaxDimension:      envPositiveInt(logger, "NODE_IMAGE_MAX_DIMENSION", 1920),
		NodeImageBytesPerMegapixel: envInt64(logger, "NODE_IMAGE_BYTES_PER_MEGAPIXEL", 500*1024),
		AudioDir:                   envOr("AUDIO_DIR", filepath.Join(dataDir, "audio")),
		TTSSidecarURL:              envOr("TTS_SIDECAR_URL", ""),
		AIEndpointURL:              envOr("AI_ENDPOINT_URL", ""),
		AIModel:                    envOr("AI_MODEL", ""),
		AIAPIKey:                   envOr("AI_API_KEY", ""),
		SearxngURL:                 envOr("SEARXNG_URL", ""),
		AIJobTimeout:               envDuration(logger, "AI_JOB_TIMEOUT", 30*time.Minute),
		AIStreamIdleTimeout:        envDuration(logger, "AI_STREAM_IDLE_TIMEOUT", 90*time.Second),
	}
	cfg.AIProviders = aiProviders(logger, cfg.AIEndpointURL, cfg.AIModel, cfg.AIAPIKey)
	if cfg.DatabaseURL == "" {
		return Config{}, errors.New("DATABASE_URL is required")
	}
	if os.Getenv("PUBLIC_BASE_URL") == "" {
		logger.Warn("config: PUBLIC_BASE_URL unset, using default", "default", cfg.PublicBaseURL)
	}
	return cfg, nil
}

// aiProviders builds the ordered failover list. AI_PROVIDERS (a JSON array)
// wins when present; each entry needs an endpoint and model (invalid ones are
// warned and skipped) and may name an env var holding its API key via
// "api_key_env", resolved here so the JSON itself never carries a secret. When
// AI_PROVIDERS is unset or yields nothing usable, the legacy single-endpoint
// vars become one "default" provider. An empty result disables AI drafting.
func aiProviders(logger *slog.Logger, legacyEndpoint, legacyModel, legacyKey string) []AIProvider {
	raw := strings.TrimSpace(os.Getenv("AI_PROVIDERS"))
	if raw != "" {
		var entries []struct {
			Name      string `json:"name"`
			Endpoint  string `json:"endpoint"`
			Model     string `json:"model"`
			APIKeyEnv string `json:"api_key_env"`
		}
		if err := json.Unmarshal([]byte(raw), &entries); err != nil {
			logger.Warn("config: AI_PROVIDERS is not valid JSON, AI drafting disabled", "err", err)
			return nil
		}
		out := make([]AIProvider, 0, len(entries))
		for i, e := range entries {
			endpoint := strings.TrimSpace(e.Endpoint)
			model := strings.TrimSpace(e.Model)
			if endpoint == "" || model == "" {
				logger.Warn("config: AI_PROVIDERS entry missing endpoint or model, skipping", "index", i, "name", e.Name)
				continue
			}
			name := strings.TrimSpace(e.Name)
			if name == "" {
				name = "provider-" + strconv.Itoa(i)
			}
			key := ""
			if envName := strings.TrimSpace(e.APIKeyEnv); envName != "" {
				key = os.Getenv(envName)
				if key == "" {
					logger.Warn("config: AI_PROVIDERS api_key_env is unset", "provider", name, "api_key_env", envName)
				}
			}
			out = append(out, AIProvider{Name: name, Endpoint: endpoint, Model: model, APIKey: key})
		}
		if len(out) > 0 {
			return out
		}
		// AI_PROVIDERS was set but produced nothing usable — treat AI as
		// disabled rather than silently falling back to the legacy vars,
		// which would mask the misconfiguration.
		return nil
	}
	if strings.TrimSpace(legacyEndpoint) == "" {
		return nil
	}
	return []AIProvider{{Name: "default", Endpoint: legacyEndpoint, Model: legacyModel, APIKey: legacyKey}}
}

// LogLevelFromEnv returns the configured startup log level. Invalid values
// fall back silently here; Load logs the warning once the logger exists.
func LogLevelFromEnv() slog.Level {
	level, ok := parseLogLevel(os.Getenv("LOG_LEVEL"))
	if !ok {
		return slog.LevelInfo
	}
	return level
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// envList splits a comma-separated env var, trims whitespace, and drops
// empty entries. Returns nil when the var is unset so callers can
// distinguish "no list configured" from "empty list".
func envList(key string) []string {
	raw := strings.TrimSpace(os.Getenv(key))
	if raw == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if v := strings.TrimSpace(p); v != "" {
			out = append(out, v)
		}
	}
	return out
}

func envLogLevel(logger *slog.Logger, key string, fallback slog.Level) slog.Level {
	raw := strings.TrimSpace(os.Getenv(key))
	if raw == "" {
		return fallback
	}
	level, ok := parseLogLevel(raw)
	if ok {
		return level
	}
	logger.Warn("config: unrecognised log level, using default", "key", key, "value", raw, "default", fallback.String())
	return fallback
}

func parseLogLevel(raw string) (slog.Level, bool) {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "debug":
		return slog.LevelDebug, true
	case "info":
		return slog.LevelInfo, true
	case "warn", "warning":
		return slog.LevelWarn, true
	case "error":
		return slog.LevelError, true
	}
	return slog.LevelInfo, false
}

// envInt64 parses a base-10 int64; anything unrecognised or non-positive
// falls back to the default and logs a warning, mirroring envBool. A zero
// or negative value would disable the limit it represents, which is
// almost certainly a misconfiguration rather than the operator's intent.
func envInt64(logger *slog.Logger, key string, fallback int64) int64 {
	raw := strings.TrimSpace(os.Getenv(key))
	if raw == "" {
		return fallback
	}
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil || v <= 0 {
		logger.Warn("config: invalid int64, using default", "key", key, "value", raw, "default", fallback)
		return fallback
	}
	return v
}

// envPositiveInt is the int-typed sibling of envInt64 for values that
// naturally fit in an int (pixel dimensions, queue depths, etc.).
func envPositiveInt(logger *slog.Logger, key string, fallback int) int {
	raw := strings.TrimSpace(os.Getenv(key))
	if raw == "" {
		return fallback
	}
	v, err := strconv.Atoi(raw)
	if err != nil || v <= 0 {
		logger.Warn("config: invalid positive int, using default", "key", key, "value", raw, "default", fallback)
		return fallback
	}
	return v
}

// envDuration parses a Go duration string (e.g. "8m", "90s"); anything
// unrecognised or non-positive falls back to the default and logs a warning.
func envDuration(logger *slog.Logger, key string, fallback time.Duration) time.Duration {
	raw := strings.TrimSpace(os.Getenv(key))
	if raw == "" {
		return fallback
	}
	d, err := time.ParseDuration(raw)
	if err != nil || d <= 0 {
		logger.Warn("config: invalid duration, using default", "key", key, "value", raw, "default", fallback)
		return fallback
	}
	return d
}

// envBool parses common true/false spellings; anything unrecognised falls
// back to the default and logs a warning so a typo doesn't silently flip
// a flag — the prior behaviour was to swallow it.
func envBool(logger *slog.Logger, key string, fallback bool) bool {
	raw := strings.TrimSpace(os.Getenv(key))
	switch strings.ToLower(raw) {
	case "":
		return fallback
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	}
	logger.Warn("config: unrecognised boolean, using default", "key", key, "value", raw, "default", fallback)
	return fallback
}
