// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const canEditNode = `-- name: CanEditNode :one
SELECT node_action_allowed(n.edit_policy, n.created_by, $2::uuid)::bool AS allowed
FROM nodes n WHERE n.id = $1
`

type CanEditNodeParams struct {
	ID       uuid.UUID  `json:"id"`
	ViewerID *uuid.UUID `json:"viewer_id"`
}

// True when `viewer` is permitted to edit `node` under its edit_policy.
// Implemented in SQL so handlers can call it without re-implementing the
// mutual-follow logic.
func (q *Queries) CanEditNode(ctx context.Context, arg CanEditNodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, canEditNode, arg.ID, arg.ViewerID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const canViewNode = `-- name: CanViewNode :one
SELECT node_visible_to(n.*, $2::uuid)::bool AS visible
FROM nodes n
WHERE n.id = $1
`

type CanViewNodeParams struct {
	ID       uuid.UUID  `json:"id"`
	ViewerID *uuid.UUID `json:"viewer_id"`
}

func (q *Queries) CanViewNode(ctx context.Context, arg CanViewNodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, canViewNode, arg.ID, arg.ViewerID)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const countEdgesForNode = `-- name: CountEdgesForNode :one
SELECT count(*) FROM edges WHERE from_node = $1 OR to_node = $1
`

// Total edges (incoming + outgoing) that would cascade-delete if the node
// were removed. Used on the deletion confirmation page.
func (q *Queries) CountEdgesForNode(ctx context.Context, fromNode uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEdgesForNode, fromNode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodes = `-- name: CountNodes :one
SELECT count(*) FROM nodes
`

func (q *Queries) CountNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOtherUserPinsForNode = `-- name: CountOtherUserPinsForNode :one
SELECT count(*) FROM user_node_pins WHERE node_id = $1 AND user_id <> $2
`

type CountOtherUserPinsForNodeParams struct {
	NodeID uuid.UUID `json:"node_id"`
	UserID uuid.UUID `json:"user_id"`
}

// Pins on this node by users other than the node's author. The author's own
// pin is excluded — they obviously consent to losing it. Other users' pins
// are surfaced on the confirmation page so the author knows what cascades.
func (q *Queries) CountOtherUserPinsForNode(ctx context.Context, arg CountOtherUserPinsForNodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherUserPinsForNode, arg.NodeID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
    type,
    title,
    body,
    source_url,
    created_by,
    slug,
    visibility,
    visibility_group_id,
    group_id,
    parent_node_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, type, title, body, source_url, created_by, created_at, updated_at, search_tsv, slug, visibility, edit_policy, parent_node_id, group_id, visibility_group_id, deleted_at, language
`

type CreateNodeParams struct {
	Type              NodeType       `json:"type"`
	Title             string         `json:"title"`
	Body              string         `json:"body"`
	SourceUrl         *string        `json:"source_url"`
	CreatedBy         uuid.UUID      `json:"created_by"`
	Slug              string         `json:"slug"`
	Visibility        VisibilityKind `json:"visibility"`
	VisibilityGroupID *uuid.UUID     `json:"visibility_group_id"`
	GroupID           *uuid.UUID     `json:"group_id"`
	ParentNodeID      *uuid.UUID     `json:"parent_node_id"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.SourceUrl,
		arg.CreatedBy,
		arg.Slug,
		arg.Visibility,
		arg.VisibilityGroupID,
		arg.GroupID,
		arg.ParentNodeID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchTsv,
		&i.Slug,
		&i.Visibility,
		&i.EditPolicy,
		&i.ParentNodeID,
		&i.GroupID,
		&i.VisibilityGroupID,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, type, title, body, source_url, created_by, created_at, updated_at, search_tsv, slug, visibility, edit_policy, parent_node_id, group_id, visibility_group_id, deleted_at, language FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchTsv,
		&i.Slug,
		&i.Visibility,
		&i.EditPolicy,
		&i.ParentNodeID,
		&i.GroupID,
		&i.VisibilityGroupID,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const getNodeBySlug = `-- name: GetNodeBySlug :one
SELECT id, type, title, body, source_url, created_by, created_at, updated_at, search_tsv, slug, visibility, edit_policy, parent_node_id, group_id, visibility_group_id, deleted_at, language FROM nodes WHERE slug = $1
`

func (q *Queries) GetNodeBySlug(ctx context.Context, slug string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeBySlug, slug)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchTsv,
		&i.Slug,
		&i.Visibility,
		&i.EditPolicy,
		&i.ParentNodeID,
		&i.GroupID,
		&i.VisibilityGroupID,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const listNodesAuthoredByForViewer = `-- name: ListNodesAuthoredByForViewer :many
SELECT id, type, title, body, source_url, created_by, created_at, updated_at, search_tsv, slug, visibility, edit_policy, parent_node_id, group_id, visibility_group_id, deleted_at, language FROM nodes n
WHERE n.created_by = $1
  AND n.type <> 'comment'
  AND n.deleted_at IS NULL
  AND node_visible_to(n.*, $2::uuid)
ORDER BY n.created_at DESC
LIMIT $3
`

type ListNodesAuthoredByForViewerParams struct {
	AuthorID    uuid.UUID  `json:"author_id"`
	ViewerID    *uuid.UUID `json:"viewer_id"`
	ResultLimit int32      `json:"result_limit"`
}

// Nodes a user has authored, most recent first — for the "Authored" section
// on a profile page. Filtered through node_visible_to() so a visitor only
// sees nodes they're entitled to. Comments are excluded; a future profile
// section can surface them separately.
func (q *Queries) ListNodesAuthoredByForViewer(ctx context.Context, arg ListNodesAuthoredByForViewerParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesAuthoredByForViewer, arg.AuthorID, arg.ViewerID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.SourceUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchTsv,
			&i.Slug,
			&i.Visibility,
			&i.EditPolicy,
			&i.ParentNodeID,
			&i.GroupID,
			&i.VisibilityGroupID,
			&i.DeletedAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByType = `-- name: ListNodesByType :many
SELECT id, type, title, body, source_url, created_by, created_at, updated_at, search_tsv, slug, visibility, edit_policy, parent_node_id, group_id, visibility_group_id, deleted_at, language FROM nodes
WHERE type = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListNodesByTypeParams struct {
	Type  NodeType `json:"type"`
	Limit int32    `json:"limit"`
}

func (q *Queries) ListNodesByType(ctx context.Context, arg ListNodesByTypeParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByType, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.SourceUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchTsv,
			&i.Slug,
			&i.Visibility,
			&i.EditPolicy,
			&i.ParentNodeID,
			&i.GroupID,
			&i.VisibilityGroupID,
			&i.DeletedAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNodesForViewer = `-- name: ListRecentNodesForViewer :many
SELECT n.id, n.slug, n.type, n.title, n.body, n.created_at, u.username AS author_username,
  (SELECT count(*) FROM user_node_pins p WHERE p.node_id = n.id AND p.kind = 'supports')::bigint AS supports_count,
  (SELECT count(*) FROM user_node_pins p WHERE p.node_id = n.id AND p.kind = 'opposes')::bigint AS opposes_count
FROM nodes n
JOIN users u ON u.id = n.created_by
WHERE n.type <> 'comment'
  AND n.deleted_at IS NULL
  AND node_visible_to(n.*, $2::uuid)
ORDER BY (
    (1.0 + (SELECT count(*) FROM user_node_pins p WHERE p.node_id = n.id))::float8
        / power(extract(epoch FROM (now() - n.created_at)) / 3600.0 + 2.0, 1.5)
  + 0.3 * (
        (SELECT count(*) FROM user_node_pins p
           WHERE p.node_id = n.id
             AND p.created_at > now() - interval '24 hours')
      + (SELECT count(*) FROM edges e
         JOIN nodes c ON c.id = e.from_node
           WHERE e.to_node = n.id
             AND e.kind = 'comments_on'
             AND c.deleted_at IS NULL
             AND c.created_at > now() - interval '24 hours')
    )::float8
  ) DESC,
  n.created_at DESC
LIMIT $1
`

type ListRecentNodesForViewerParams struct {
	Limit    int32      `json:"limit"`
	ViewerID *uuid.UUID `json:"viewer_id"`
}

type ListRecentNodesForViewerRow struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Type           NodeType           `json:"type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AuthorUsername string             `json:"author_username"`
	SupportsCount  int64              `json:"supports_count"`
	OpposesCount   int64              `json:"opposes_count"`
}

// Home page feed and landing-page teaser. node_visible_to() handles the
// per-row visibility check; viewer_id is NULL for logged-out users (only
// public nodes match). Comments are excluded from the feed — they show up
// inline under their target node and in the argument graph, not as
// standalone entries. body is returned so callers that want a preview
// snippet (landing cards) can render an excerpt; the home feed simply
// ignores it.
//
// Ordering combines two terms so the feed surfaces both new posts and old
// posts that are "going off" right now:
//
//	base     = (1 + lifetime pins) / (age_hours + 2) ^ 1.5
//	velocity = 0.3 * (pins in last 24h + 1-hop comments in last 24h)
//	score    = base + velocity
//
// The base term is Hacker-News-style: it rewards lifetime engagement and
// decays with the node's creation age (gravity 1.5 is gentler than HN's
// 1.8, so multi-day-old posts still register). The velocity term ignores
// creation age entirely, so a dormant week-old node with a recent burst of
// attention can outrank brand-new lonely posts. Comment activity is
// counted 1-hop only — replies-to-replies don't bubble through, which
// keeps the signal a deliberate "engagement with this post" rather than
// "drama anywhere downstream". n.created_at DESC is the tiebreaker so
// identical scores resolve newest-first.
func (q *Queries) ListRecentNodesForViewer(ctx context.Context, arg ListRecentNodesForViewerParams) ([]ListRecentNodesForViewerRow, error) {
	rows, err := q.db.Query(ctx, listRecentNodesForViewer, arg.Limit, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentNodesForViewerRow
	for rows.Next() {
		var i ListRecentNodesForViewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.SupportsCount,
			&i.OpposesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewsForTopic = `-- name: ListViewsForTopic :many
SELECT
    n.id,
    n.slug,
    n.title,
    n.body,
    n.created_at,
    u.username AS author_username,
    u.profile_image_path AS author_profile_image_path,
    (
        SELECT count(*)::bigint
        FROM nodes c
        WHERE c.type = 'comment'
          AND c.deleted_at IS NULL
          AND EXISTS (
              SELECT 1 FROM edges e1
              WHERE e1.from_node = c.id AND e1.kind = 'comments_on'
                AND (
                    e1.to_node = n.id
                    OR EXISTS (
                        SELECT 1 FROM edges e2
                        WHERE e2.from_node = e1.to_node
                          AND e2.kind = 'comments_on'
                          AND e2.to_node = n.id
                    )
                )
          )
    ) AS comment_count
FROM nodes n
JOIN users u ON u.id = n.created_by
WHERE n.type = 'view'
  AND n.parent_node_id = $1::uuid
  AND n.deleted_at IS NULL
  AND node_visible_to(n.*, $2::uuid)
ORDER BY n.created_at DESC
LIMIT $3
`

type ListViewsForTopicParams struct {
	TopicID     uuid.UUID  `json:"topic_id"`
	ViewerID    *uuid.UUID `json:"viewer_id"`
	ResultLimit int32      `json:"result_limit"`
}

type ListViewsForTopicRow struct {
	ID                     uuid.UUID          `json:"id"`
	Slug                   string             `json:"slug"`
	Title                  string             `json:"title"`
	Body                   string             `json:"body"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	AuthorUsername         string             `json:"author_username"`
	AuthorProfileImagePath string             `json:"author_profile_image_path"`
	CommentCount           int64              `json:"comment_count"`
}

// Topic pages render their child views as a thread feed. parent_node_id is
// the canonical hierarchy link; node_visible_to() keeps group/list/private
// child views hidden from viewers outside their audience.
//
// comment_count walks 'comments_on' edges up to two hops deep (top-level
// comments attached to the view, plus their replies). Soft-deleted
// comments are excluded so the badge matches what the viewer actually
// sees. The depth limit mirrors the application's one-level-reply rule.
func (q *Queries) ListViewsForTopic(ctx context.Context, arg ListViewsForTopicParams) ([]ListViewsForTopicRow, error) {
	rows, err := q.db.Query(ctx, listViewsForTopic, arg.TopicID, arg.ViewerID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListViewsForTopicRow
	for rows.Next() {
		var i ListViewsForTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorProfileImagePath,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickerSearchNodes = `-- name: PickerSearchNodes :many
SELECT n.id, n.type, n.title
FROM nodes n
WHERE n.id != $1
  AND n.type <> 'comment'
  AND n.deleted_at IS NULL
  AND n.title %> $2::text
  AND node_visible_to(n.*, $3::uuid)
ORDER BY word_similarity($2::text, n.title) DESC, n.title ASC
LIMIT 50
`

type PickerSearchNodesParams struct {
	SourceID uuid.UUID  `json:"source_id"`
	Query    string     `json:"query"`
	ViewerID *uuid.UUID `json:"viewer_id"`
}

type PickerSearchNodesRow struct {
	ID    uuid.UUID `json:"id"`
	Type  NodeType  `json:"type"`
	Title string    `json:"title"`
}

// Trigram fuzzy match against the title for the edge-creation picker.
// Handles prefix ("nuc" → "Nuclear"), infix ("uclear" → "Nuclear") and
// typo tolerance ("nucear" → "Nuclear") in one mechanism. The %> operator
// uses the GIN trigram index and respects pg_trgm.word_similarity_threshold,
// which we set to 0.25 in pgxpool.AfterConnect. Excludes the source node
// and skips nodes the viewer can't see. Raw user text is safe here —
// pg_trgm operators take plain text, no query syntax to escape.
func (q *Queries) PickerSearchNodes(ctx context.Context, arg PickerSearchNodesParams) ([]PickerSearchNodesRow, error) {
	rows, err := q.db.Query(ctx, pickerSearchNodes, arg.SourceID, arg.Query, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PickerSearchNodesRow
	for rows.Next() {
		var i PickerSearchNodesRow
		if err := rows.Scan(&i.ID, &i.Type, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodes = `-- name: SearchNodes :many
SELECT
    n.id, n.slug, n.type, n.title, n.body, n.source_url, n.created_by,
    n.created_at, n.updated_at,
    u.username AS author_username,
    CASE WHEN n.search_tsv @@ websearch_to_tsquery('english', $1::text)
         THEN 1.0 + ts_rank(n.search_tsv, websearch_to_tsquery('english', $1::text))
         ELSE word_similarity($1::text, n.title)::real
    END AS rank,
    ts_headline('english', n.body, websearch_to_tsquery('english', $1::text),
                'StartSel=«HL», StopSel=«/HL», MaxFragments=1, MaxWords=24, MinWords=8')::text AS excerpt
FROM nodes n
JOIN users u ON u.id = n.created_by
WHERE (n.search_tsv @@ websearch_to_tsquery('english', $1::text)
       OR n.title %> $1::text)
  AND n.type <> 'comment'
  AND n.deleted_at IS NULL
  AND node_visible_to(n.*, $2::uuid)
ORDER BY rank DESC, n.created_at DESC
LIMIT $3
`

type SearchNodesParams struct {
	Query       string     `json:"query"`
	ViewerID    *uuid.UUID `json:"viewer_id"`
	ResultLimit int32      `json:"result_limit"`
}

type SearchNodesRow struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Type           NodeType           `json:"type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	SourceUrl      *string            `json:"source_url"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
	Rank           float32            `json:"rank"`
	Excerpt        string             `json:"excerpt"`
}

// Hybrid full-text + fuzzy search. tsvector handles stems, stop-words, and
// phrase quotes via websearch_to_tsquery; pg_trgm word_similarity on the
// title catches typos and partial words ("nucear" → "Nuclear"). A row
// matches if EITHER mechanism hits.
//
// Ranking gives semantic matches a +1.0 head-start so they always sit above
// pure-fuzzy matches at the same nominal score; within each group we order
// by relevance score and then creation date as a tiebreaker.
//
// ts_headline runs over the tsquery only — fuzzy-only matches get an empty
// excerpt because the body did not contain the searched lexemes; the title
// carries enough information in that case.
//
// node_visible_to() filters out anything the viewer isn't entitled to.
func (q *Queries) SearchNodes(ctx context.Context, arg SearchNodesParams) ([]SearchNodesRow, error) {
	rows, err := q.db.Query(ctx, searchNodes, arg.Query, arg.ViewerID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesRow
	for rows.Next() {
		var i SearchNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.SourceUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.Rank,
			&i.Excerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostParents = `-- name: SearchPostParents :many
SELECT id, type, title
FROM nodes
WHERE ($1::text = '' OR type::text = $1::text)
  AND type <> 'comment'
  AND deleted_at IS NULL
  AND node_visible_to(nodes.*, $2::uuid)
  AND ($3::text = '' OR title %> $3::text)
ORDER BY
    CASE
        WHEN $1::text <> '' THEN 0
        WHEN type = 'view' THEN 0
        WHEN type = 'topic' AND parent_node_id IS NOT NULL THEN 0
        ELSE 1
    END ASC,
    CASE WHEN $3::text = '' THEN created_at ELSE NULL END DESC NULLS LAST,
    word_similarity($3::text, title) DESC,
    title ASC
LIMIT 20
`

type SearchPostParentsParams struct {
	TypeFilter string     `json:"type_filter"`
	ViewerID   *uuid.UUID `json:"viewer_id"`
	Query      string     `json:"query"`
}

type SearchPostParentsRow struct {
	ID    uuid.UUID `json:"id"`
	Type  NodeType  `json:"type"`
	Title string    `json:"title"`
}

// Parent picker for the post form. type_filter restricts to a single node
// type ('topic' when creating a view or sub-topic); leave it empty to match
// any type ('topic', 'view', or 'finding') — used when creating a finding,
// which can attach to any existing node. Fuzzy-searches titles when a query
// is given; falls back to recency order when empty so the picker is
// pre-populated. Respects node_visible_to() so viewers only see candidates
// they can post under.
//
// When type_filter is empty (finding flow), candidates are bucketed by how
// specific a parent they make: views and sub-topics first (a finding most
// naturally attaches to a concrete stance or a narrow topic), then root
// topics and other findings. Inside each bucket, the usual recency / fuzzy-
// match order applies. Single-type queries skip the bucket so the original
// order is preserved.
func (q *Queries) SearchPostParents(ctx context.Context, arg SearchPostParentsParams) ([]SearchPostParentsRow, error) {
	rows, err := q.db.Query(ctx, searchPostParents, arg.TypeFilter, arg.ViewerID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostParentsRow
	for rows.Next() {
		var i SearchPostParentsRow
		if err := rows.Scan(&i.ID, &i.Type, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET title = $2,
    body = $3,
    source_url = $4,
    visibility = $5,
    visibility_group_id = $6,
    group_id = $7,
    edit_policy = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, type, title, body, source_url, created_by, created_at, updated_at, search_tsv, slug, visibility, edit_policy, parent_node_id, group_id, visibility_group_id, deleted_at, language
`

type UpdateNodeParams struct {
	ID                uuid.UUID        `json:"id"`
	Title             string           `json:"title"`
	Body              string           `json:"body"`
	SourceUrl         *string          `json:"source_url"`
	Visibility        VisibilityKind   `json:"visibility"`
	VisibilityGroupID *uuid.UUID       `json:"visibility_group_id"`
	GroupID           *uuid.UUID       `json:"group_id"`
	EditPolicy        NodeActionPolicy `json:"edit_policy"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.SourceUrl,
		arg.Visibility,
		arg.VisibilityGroupID,
		arg.GroupID,
		arg.EditPolicy,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchTsv,
		&i.Slug,
		&i.Visibility,
		&i.EditPolicy,
		&i.ParentNodeID,
		&i.GroupID,
		&i.VisibilityGroupID,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}
