// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPinReasoning = `-- name: AddPinReasoning :exec
INSERT INTO pin_reasonings (pin_id, reasoning_id)
VALUES ($1, $2)
ON CONFLICT (pin_id, reasoning_id) DO NOTHING
`

type AddPinReasoningParams struct {
	PinID       uuid.UUID `json:"pin_id"`
	ReasoningID uuid.UUID `json:"reasoning_id"`
}

// Attach one reasoning to a pin. ON CONFLICT DO NOTHING so the same
// (pin, reasoning) pair is a harmless retry rather than an error.
func (q *Queries) AddPinReasoning(ctx context.Context, arg AddPinReasoningParams) error {
	_, err := q.db.Exec(ctx, addPinReasoning, arg.PinID, arg.ReasoningID)
	return err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM user_node_pins WHERE user_id = $1 AND node_id = $2
`

type DeletePinParams struct {
	UserID uuid.UUID `json:"user_id"`
	NodeID uuid.UUID `json:"node_id"`
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) error {
	_, err := q.db.Exec(ctx, deletePin, arg.UserID, arg.NodeID)
	return err
}

const deleteReasoningsForPin = `-- name: DeleteReasoningsForPin :exec
DELETE FROM pin_reasonings WHERE pin_id = $1
`

// Clear all attached reasonings for a pin. Combined with AddPinReasoning
// this implements "replace the set" semantics for the pin form.
func (q *Queries) DeleteReasoningsForPin(ctx context.Context, pinID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReasoningsForPin, pinID)
	return err
}

const getPinForUserAndNode = `-- name: GetPinForUserAndNode :one
SELECT
    p.id,
    p.kind,
    p.created_at
FROM user_node_pins p
WHERE p.user_id = $1 AND p.node_id = $2
`

type GetPinForUserAndNodeParams struct {
	UserID uuid.UUID `json:"user_id"`
	NodeID uuid.UUID `json:"node_id"`
}

type GetPinForUserAndNodeRow struct {
	ID        uuid.UUID          `json:"id"`
	Kind      PinKind            `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Whether and how the viewer has pinned a given node. Attached reasonings
// are loaded separately via ListReasoningsForPin so the same shape covers
// 0, 1, or many reasonings without nested aggregation here.
func (q *Queries) GetPinForUserAndNode(ctx context.Context, arg GetPinForUserAndNodeParams) (GetPinForUserAndNodeRow, error) {
	row := q.db.QueryRow(ctx, getPinForUserAndNode, arg.UserID, arg.NodeID)
	var i GetPinForUserAndNodeRow
	err := row.Scan(&i.ID, &i.Kind, &i.CreatedAt)
	return i, err
}

const listPinsByUser = `-- name: ListPinsByUser :many
SELECT
    p.id,
    p.node_id,
    p.kind,
    p.created_at,
    n.slug  AS node_slug,
    n.type  AS node_type,
    n.title AS node_title
FROM user_node_pins p
JOIN nodes n ON n.id = p.node_id
WHERE p.user_id = $1
  AND node_visible_to(n.*, $2::uuid)
ORDER BY p.created_at DESC
`

type ListPinsByUserParams struct {
	UserID   uuid.UUID  `json:"user_id"`
	ViewerID *uuid.UUID `json:"viewer_id"`
}

type ListPinsByUserRow struct {
	ID        uuid.UUID          `json:"id"`
	NodeID    uuid.UUID          `json:"node_id"`
	Kind      PinKind            `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	NodeSlug  string             `json:"node_slug"`
	NodeType  NodeType           `json:"node_type"`
	NodeTitle string             `json:"node_title"`
}

// A user's pins with the joined node — for the "On my profile" section on
// a profile page. Reasonings are loaded separately via ListReasoningsForPins
// to avoid row-multiplying joins. node_visible_to() hides pins whose
// underlying node the viewer isn't entitled to see.
func (q *Queries) ListPinsByUser(ctx context.Context, arg ListPinsByUserParams) ([]ListPinsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPinsByUser, arg.UserID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinsByUserRow
	for rows.Next() {
		var i ListPinsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.CreatedAt,
			&i.NodeSlug,
			&i.NodeType,
			&i.NodeTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReasoningsForPin = `-- name: ListReasoningsForPin :many
SELECT n.id, n.slug, n.title
FROM pin_reasonings pr
JOIN nodes n ON n.id = pr.reasoning_id
WHERE pr.pin_id = $1
  AND node_visible_to(n.*, $2::uuid)
ORDER BY pr.created_at ASC
`

type ListReasoningsForPinParams struct {
	PinID    uuid.UUID  `json:"pin_id"`
	ViewerID *uuid.UUID `json:"viewer_id"`
}

type ListReasoningsForPinRow struct {
	ID    uuid.UUID `json:"id"`
	Slug  string    `json:"slug"`
	Title string    `json:"title"`
}

// Reasonings attached to a single pin, oldest-attached first so the order
// the user added them is preserved. Hidden reasonings are filtered out.
func (q *Queries) ListReasoningsForPin(ctx context.Context, arg ListReasoningsForPinParams) ([]ListReasoningsForPinRow, error) {
	rows, err := q.db.Query(ctx, listReasoningsForPin, arg.PinID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReasoningsForPinRow
	for rows.Next() {
		var i ListReasoningsForPinRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReasoningsForPins = `-- name: ListReasoningsForPins :many
SELECT pr.pin_id, n.id, n.slug, n.title
FROM pin_reasonings pr
JOIN nodes n ON n.id = pr.reasoning_id
WHERE pr.pin_id = ANY($1::uuid[])
  AND node_visible_to(n.*, $2::uuid)
ORDER BY pr.created_at ASC
`

type ListReasoningsForPinsParams struct {
	PinIds   []uuid.UUID `json:"pin_ids"`
	ViewerID *uuid.UUID  `json:"viewer_id"`
}

type ListReasoningsForPinsRow struct {
	PinID uuid.UUID `json:"pin_id"`
	ID    uuid.UUID `json:"id"`
	Slug  string    `json:"slug"`
	Title string    `json:"title"`
}

// Batch-load reasonings for multiple pins at once — used to avoid N+1 when
// rendering a profile's pin list. Result includes the pin_id so callers
// can group by pin. Hidden reasonings are filtered out.
func (q *Queries) ListReasoningsForPins(ctx context.Context, arg ListReasoningsForPinsParams) ([]ListReasoningsForPinsRow, error) {
	rows, err := q.db.Query(ctx, listReasoningsForPins, arg.PinIds, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReasoningsForPinsRow
	for rows.Next() {
		var i ListReasoningsForPinsRow
		if err := rows.Scan(
			&i.PinID,
			&i.ID,
			&i.Slug,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPin = `-- name: SetPin :one
INSERT INTO user_node_pins (user_id, node_id, kind)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, node_id) DO UPDATE SET
    kind = EXCLUDED.kind,
    created_at = now()
RETURNING id
`

type SetPinParams struct {
	UserID uuid.UUID `json:"user_id"`
	NodeID uuid.UUID `json:"node_id"`
	Kind   PinKind   `json:"kind"`
}

// Upsert: changing your stance from supports → opposes (or any other
// transition) replaces the existing row in place. created_at is reset on
// update so the profile shows the most recent stance change first. Returns
// the pin's id so callers can attach reasonings to it.
func (q *Queries) SetPin(ctx context.Context, arg SetPinParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setPin, arg.UserID, arg.NodeID, arg.Kind)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
