// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptGroupInvite(ctx context.Context, arg AcceptGroupInviteParams) (int64, error)
	// Idempotent insert. If the user is already a member the existing row is
	// left untouched, so an admin re-adding an existing admin or editor by
	// username can't silently downgrade them to member. Role changes go
	// through SetGroupMemberRole.
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	AttachTag(ctx context.Context, arg AttachTagParams) error
	// True when `viewer` is permitted to edit `node` under its edit_policy.
	// Implemented in SQL so handlers can call it without re-implementing the
	// mutual-follow logic.
	CanEditNode(ctx context.Context, arg CanEditNodeParams) (bool, error)
	// Single-group visibility probe used by resolveGroup() to gate the
	// detail page for non-public groups. Mirrors the visibility branches
	// in ListVisibleGroups: members always pass, connections groups pass
	// when viewer mutually follows the owner, private groups require
	// membership.
	CanViewGroup(ctx context.Context, arg CanViewGroupParams) (bool, error)
	CanViewNode(ctx context.Context, arg CanViewNodeParams) (bool, error)
	// Used to refuse demotions that would leave the instance with no admins.
	// A site with zero admins can't be managed through the UI; recovery
	// requires either ADMIN_USERS at boot or a DB-level fix.
	CountAdmins(ctx context.Context) (int64, error)
	// Total edges (incoming + outgoing) that would cascade-delete if the node
	// were removed. Used on the deletion confirmation page.
	CountEdgesForNode(ctx context.Context, fromNode uuid.UUID) (int64, error)
	CountFollowers(ctx context.Context, followedID uuid.UUID) (int64, error)
	CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error)
	CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error)
	CountIdentitiesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountNodes(ctx context.Context) (int64, error)
	// Used on the admin delete-user confirmation page so the admin can see
	// the blast radius before clicking through.
	CountNodesAuthoredBy(ctx context.Context, createdBy uuid.UUID) (int64, error)
	// Pins on this node by users other than the node's author. The author's own
	// pin is excluded — they obviously consent to losing it. Other users' pins
	// are surfaced on the confirmation page so the author knows what cascades.
	CountOtherUserPinsForNode(ctx context.Context, arg CountOtherUserPinsForNodeParams) (int64, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	// Comments are stored as nodes (type='comment') attached to their target
	// via a 'comments_on' edge. Top-level comments point at the discussed
	// node (view, topic, finding, ...); replies point at the parent comment.
	// The single reply level is enforced at write time so the thread UI's
	// two-level layout stays valid.
	// Creates a comment node and the comments_on edge linking it to its target
	// in one statement. Branches on parent_id:
	//   parent_id IS NULL → top-level comment on node_id (any non-comment node)
	//   parent_id IS NOT  → reply, where parent_id must already be a top-level
	//                       comment of node_id (its comments_on points at node_id)
	// Visibility, group_id, and visibility_group_id are inherited from node_id
	// so private/group conversations shield their replies too. The caller
	// supplies comment_id and comment_slug — slug is the synthetic 'c-<uuid>'
	// pattern; it satisfies the NOT NULL UNIQUE constraint without being
	// URL-exposed (redirects use the parent node's slug).
	CreateCommentNode(ctx context.Context, arg CreateCommentNodeParams) (CreateCommentNodeRow, error)
	CreateEdge(ctx context.Context, arg CreateEdgeParams) (Edge, error)
	// Idempotent: re-following is a no-op rather than an error so the button
	// handler doesn't need to disambiguate states.
	CreateFollow(ctx context.Context, arg CreateFollowParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupInvite(ctx context.Context, arg CreateGroupInviteParams) (GroupInvite, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateNodeImage(ctx context.Context, arg CreateNodeImageParams) (NodeImage, error)
	// Writes a new revision for a node, picking the next revision number atomically
	// by reading max(revision)+1 in the same statement. The UNIQUE(node_id,
	// revision) constraint backs this up if two updates race.
	CreateNodeRevision(ctx context.Context, arg CreateNodeRevisionParams) (NodeRevision, error)
	CreateNodeVideo(ctx context.Context, arg CreateNodeVideoParams) (NodeVideo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthIdentityForUser(ctx context.Context, arg DeleteAuthIdentityForUserParams) error
	// Page-node editors can delete only edges touching the page node they are
	// editing. The handler enforces edit permission on that node; this WHERE
	// clause keeps the edge membership check in the database mutation too.
	DeleteEdge(ctx context.Context, arg DeleteEdgeParams) (int64, error)
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteNode(ctx context.Context, id uuid.UUID) error
	// Returns the number of removed rows so callers can 404 a request to
	// unpin a node the user never pinned. Mirrors the pattern on the edge
	// delete / highlight / unhighlight queries.
	DeletePin(ctx context.Context, arg DeletePinParams) (int64, error)
	// Used by the "replace all tags" path on node update — the handler deletes
	// the existing rows and re-inserts the new set.
	DeleteTagsForNode(ctx context.Context, nodeID uuid.UUID) error
	// Hard-delete the user row. FK cascades take care of follows, pins,
	// comments, group memberships, auth identities, nodes, and edges; node
	// revisions keep their content but lose the edited_by attribution
	// (ON DELETE SET NULL).
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Walk the parent chain to the topmost ancestor. Returns the id only when
	// that ancestor is a topic; otherwise no row (callers reject the upload).
	// The `parent_node_id IS NOT NULL` cycle guard mirrors node_visible_to() —
	// a malformed cycle would otherwise loop forever.
	FindRootTopicForNode(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Loads a single comment attached (one or two hops) to the named node.
	// Used by the edit/update/delete handlers so a comment from one view
	// can't be touched via another view's URL.
	GetCommentForNode(ctx context.Context, arg GetCommentForNodeParams) (GetCommentForNodeRow, error)
	// One round-trip lookup the profile page uses to render the button: does
	// the viewer follow this profile, and does the profile follow the viewer
	// back (mutual = connection)?
	GetFollowState(ctx context.Context, arg GetFollowStateParams) (GetFollowStateRow, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupBySlug(ctx context.Context, slug string) (Group, error)
	GetGroupMembership(ctx context.Context, arg GetGroupMembershipParams) (GroupMembership, error)
	GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (AuthIdentity, error)
	GetIdentityForUser(ctx context.Context, arg GetIdentityForUserParams) (AuthIdentity, error)
	// The newest revision for a node. The update handler reads this to decide
	// whether the incoming save actually changes anything — if title/body/tags
	// all match, we skip writing a spurious duplicate.
	GetLatestNodeRevision(ctx context.Context, nodeID uuid.UUID) (NodeRevision, error)
	GetNode(ctx context.Context, id uuid.UUID) (Node, error)
	GetNodeBySlug(ctx context.Context, slug string) (Node, error)
	// A single revision identified by (node_id, revision). Returns the full body
	// so the snapshot view can render it.
	GetNodeRevision(ctx context.Context, arg GetNodeRevisionParams) (GetNodeRevisionRow, error)
	// Lookup used by the password-login flow: find the user by email AND the
	// bcrypt hash of their password identity in one round-trip.
	GetPasswordIdentityForLogin(ctx context.Context, email string) (GetPasswordIdentityForLoginRow, error)
	GetPasswordIdentityForUser(ctx context.Context, userID uuid.UUID) (AuthIdentity, error)
	// Whether and how the viewer has pinned a given node. Pins now carry
	// only the stance — findings live as first-class graph nodes attached
	// through edges, not bolted onto the pin record.
	GetPinForUserAndNode(ctx context.Context, arg GetPinForUserAndNodeParams) (GetPinForUserAndNodeRow, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Permanent delete used by staff. Removes the comment plus its direct
	// replies (comment nodes whose comments_on edge points at this comment).
	// The matching edges are removed by their own ON DELETE CASCADE.
	HardDeleteComment(ctx context.Context, id uuid.UUID) (int64, error)
	// Promote an edge into the highlights section from the perspective of
	// `pov_node`, which must be one of the edge's endpoints. The rank is the
	// next-highest across the existing highlights on that side, so the new
	// card lands at the bottom by default. The "other" endpoint must be a
	// finding — the highlights section is for findings only. If either check
	// fails the WHERE clause filters the row out and nothing changes.
	HighlightEdge(ctx context.Context, arg HighlightEdgeParams) (int64, error)
	IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error)
	// Tag list with how many nodes carry each tag — for the /tags index page.
	// Counts only nodes the viewer is allowed to see (public, plus connections-
	// /list-/private-scoped nodes the viewer has access to). Tags whose visible
	// node count is zero are dropped so we don't leak the existence of tags that
	// only live on private nodes.
	ListAllTagsForViewer(ctx context.Context, viewerID *uuid.UUID) ([]ListAllTagsForViewerRow, error)
	// Edges among a known set of visible graph nodes, used by server-side graph
	// search results.
	ListArgumentGraphEdgesForNodeIDs(ctx context.Context, arg ListArgumentGraphEdgesForNodeIDsParams) ([]ListArgumentGraphEdgesForNodeIDsRow, error)
	// Edges whose endpoints are both present in the same recent visible-node
	// slice. Endpoint visibility gates edge visibility because edges do not carry
	// separate visibility policy.
	ListArgumentGraphEdgesForViewer(ctx context.Context, arg ListArgumentGraphEdgesForViewerParams) ([]ListArgumentGraphEdgesForViewerRow, error)
	// Returns every visible node within max_hops edges of any seed_id, including
	// the seeds themselves. Used by the graph search path so a single direct
	// match still arrives at the browser with enough surrounding context for the
	// client-side depth slider to walk. Cycles are de-duplicated by the UNION;
	// the outer LIMIT is the safety net against pathologically dense subgraphs.
	ListArgumentGraphNeighborhood(ctx context.Context, arg ListArgumentGraphNeighborhoodParams) ([]ListArgumentGraphNeighborhoodRow, error)
	// Recent visible nodes for the graph canvas. The graph viewer is intentionally
	// bounded so a public instance cannot ship an unbounded graph into the page.
	// Comment nodes are included here so threads show up alongside their target
	// in the graph; deleted (soft-removed) nodes are excluded.
	//
	// parent_slug is the slug of the root non-comment ancestor for comment rows
	// (NULL otherwise). The graph inspector uses it to route "Open node" to
	// /nodes/<parent_slug>#comment-<id> so a comment selected in the graph opens
	// the discussion page already anchored at the comment. One or two hops cover
	// the application's max reply depth (top-level → reply); deeper chains would
	// still resolve to the highest reachable non-comment via the second branch.
	ListArgumentGraphNodesForViewer(ctx context.Context, arg ListArgumentGraphNodesForViewerParams) ([]ListArgumentGraphNodesForViewerRow, error)
	// Visible node IDs matching the active graph-viewer filters. All filter
	// parameters are nullable / sentinel-blank: pass NULL (or an empty array
	// for tag_names) to skip a predicate. The seeds returned here feed the
	// neighborhood walk, so the depth slider can still expand context around
	// whatever set the filters carve out. Combining filters behaves as AND
	// from the user's perspective; tag_names itself requires every named
	// tag to be attached to a node (intersection, not union). Free-text
	// search is intentionally not part of this query — it stays in
	// SearchNodes (which uses tsvector + trigram) and is intersected at the
	// Go layer when both are active. The cap matches the canvas budget.
	ListArgumentGraphSeeds(ctx context.Context, arg ListArgumentGraphSeedsParams) ([]uuid.UUID, error)
	// Returns top-level comments attached to node_id, plus their direct
	// replies. parent_id is NULL on top-level rows and set to the parent
	// comment's id on reply rows. Soft-deleted comments stay in the result
	// so the "comment removed" placeholder keeps the thread structure.
	ListCommentsForNode(ctx context.Context, nodeID uuid.UUID) ([]ListCommentsForNodeRow, error)
	// People the user has a mutual follow with — drives the "friends bubble"
	// graph view. Alphabetical for stable rendering.
	ListConnections(ctx context.Context, followerID uuid.UUID) ([]ListConnectionsRow, error)
	// Outgoing edges with the destination node's title and type joined in,
	// ready to render the "this node points at..." section of the legend.
	// position is NULL for legend-only edges and an integer rank when the
	// FROM-node has highlighted it. node_visible_to() hides edges whose
	// endpoint the viewer isn't entitled to.
	ListEdgesFromNodeForViewer(ctx context.Context, arg ListEdgesFromNodeForViewerParams) ([]ListEdgesFromNodeForViewerRow, error)
	// Incoming edges, similar shape — for "what points at this node".
	// to_position is the rank when this node (the TO endpoint) has highlighted
	// the edge from its side; NULL keeps it in the legend only.
	ListEdgesToNodeForViewer(ctx context.Context, arg ListEdgesToNodeForViewerParams) ([]ListEdgesToNodeForViewerRow, error)
	// Users that follow $1.
	ListFollowers(ctx context.Context, followedID uuid.UUID) ([]ListFollowersRow, error)
	// Users that $1 follows.
	ListFollowing(ctx context.Context, followerID uuid.UUID) ([]ListFollowingRow, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error)
	ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]ListGroupsForUserRow, error)
	// All edges where `node_id` is an endpoint AND that endpoint has marked
	// the edge as highlighted (position when from_node, to_position when
	// to_node). Returns the "other" endpoint regardless of direction so the
	// highlight card can render uniformly. direction tells the UI which
	// active/passive label to apply. Restricted to finding targets so the
	// "Key findings" section semantically matches its name.
	ListHighlightedEdgesForNode(ctx context.Context, arg ListHighlightedEdgesForNodeParams) ([]ListHighlightedEdgesForNodeRow, error)
	ListIdentitiesForUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error)
	ListNodeImagesByUploader(ctx context.Context, uploadedBy uuid.UUID) ([]ListNodeImagesByUploaderRow, error)
	ListNodeImagesForRoot(ctx context.Context, rootTopicID uuid.UUID) ([]ListNodeImagesForRootRow, error)
	// All revisions for a node, newest first. editor_username is null when the
	// user has been deleted (FK is ON DELETE SET NULL) — the UI shows "deleted
	// user" in that case.
	ListNodeRevisions(ctx context.Context, nodeID uuid.UUID) ([]ListNodeRevisionsRow, error)
	ListNodeVideosByUploader(ctx context.Context, uploadedBy uuid.UUID) ([]ListNodeVideosByUploaderRow, error)
	ListNodeVideosForRoot(ctx context.Context, rootTopicID uuid.UUID) ([]ListNodeVideosForRootRow, error)
	// Nodes a user has authored, most recent first — for the "Authored" section
	// on a profile page. Filtered through node_visible_to() so a visitor only
	// sees nodes they're entitled to. Comments are excluded; a future profile
	// section can surface them separately.
	ListNodesAuthoredByForViewer(ctx context.Context, arg ListNodesAuthoredByForViewerParams) ([]Node, error)
	ListNodesByType(ctx context.Context, arg ListNodesByTypeParams) ([]Node, error)
	ListNodesForGroupForViewer(ctx context.Context, arg ListNodesForGroupForViewerParams) ([]Node, error)
	// Nodes that carry a given tag, most recent first — for /tags/{name}.
	// Filtered through node_visible_to() so a viewer only sees nodes they can.
	ListNodesWithTagForViewer(ctx context.Context, arg ListNodesWithTagForViewerParams) ([]Node, error)
	ListPendingGroupInvitesForUser(ctx context.Context, invitedUserID uuid.UUID) ([]ListPendingGroupInvitesForUserRow, error)
	// A user's pins with the joined node — for the "On my profile" section on
	// a profile page. node_visible_to() hides pins whose underlying node the
	// viewer isn't entitled to see.
	ListPinsByUser(ctx context.Context, arg ListPinsByUserParams) ([]ListPinsByUserRow, error)
	// Home page feed. node_visible_to() handles the per-row visibility check;
	// viewer_id is NULL for logged-out users (only public nodes match).
	// Comments are excluded from the feed — they show up inline under their
	// target node and in the argument graph, not as standalone entries.
	ListRecentNodesForViewer(ctx context.Context, arg ListRecentNodesForViewerParams) ([]ListRecentNodesForViewerRow, error)
	ListTagsForNode(ctx context.Context, nodeID uuid.UUID) ([]Tag, error)
	// Roster for the admin /users page. Recent signups first; staff bubble to
	// the top so they're easy to find.
	ListUsersForAdmin(ctx context.Context) ([]User, error)
	// Topic pages render their child views as a thread feed. parent_node_id is
	// the canonical hierarchy link; node_visible_to() keeps group/list/private
	// child views hidden from viewers outside their audience.
	//
	// comment_count walks 'comments_on' edges up to two hops deep (top-level
	// comments attached to the view, plus their replies). Soft-deleted
	// comments are excluded so the badge matches what the viewer actually
	// sees. The depth limit mirrors the application's one-level-reply rule.
	ListViewsForTopic(ctx context.Context, arg ListViewsForTopicParams) ([]ListViewsForTopicRow, error)
	// Three visibility branches:
	//   public       — visible to everyone (the public/anon visitor included)
	//   connections  — visible to the owner's mutual followers + members
	//   private      — visible only to members
	// The viewer_role / is_member columns power the badge/CTA logic in the
	// groups index; member_count is a per-row aggregate so we don't need a
	// separate hit per group.
	ListVisibleGroups(ctx context.Context, viewerID *uuid.UUID) ([]ListVisibleGroupsRow, error)
	// Trigram fuzzy match against the title for the edge-creation picker.
	// Handles prefix ("nuc" → "Nuclear"), infix ("uclear" → "Nuclear") and
	// typo tolerance ("nucear" → "Nuclear") in one mechanism. The %> operator
	// uses the GIN trigram index and respects pg_trgm.word_similarity_threshold,
	// which we set to 0.25 in pgxpool.AfterConnect. Excludes the source node
	// and skips nodes the viewer can't see. Raw user text is safe here —
	// pg_trgm operators take plain text, no query syntax to escape.
	PickerSearchNodes(ctx context.Context, arg PickerSearchNodesParams) ([]PickerSearchNodesRow, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	// Trigram fuzzy match against the group name. Mirrors SearchUsers but
	// additionally gates each row by the viewer's right to see the group
	// (see ListVisibleGroups for the visibility branches). The %> threshold
	// is the same one the picker uses elsewhere (set in pgxpool.AfterConnect).
	SearchGroups(ctx context.Context, arg SearchGroupsParams) ([]SearchGroupsRow, error)
	// Hybrid full-text + fuzzy search. tsvector handles stems, stop-words, and
	// phrase quotes via websearch_to_tsquery; pg_trgm word_similarity on the
	// title catches typos and partial words ("nucear" → "Nuclear"). A row
	// matches if EITHER mechanism hits.
	//
	// Ranking gives semantic matches a +1.0 head-start so they always sit above
	// pure-fuzzy matches at the same nominal score; within each group we order
	// by relevance score and then creation date as a tiebreaker.
	//
	// ts_headline runs over the tsquery only — fuzzy-only matches get an empty
	// excerpt because the body did not contain the searched lexemes; the title
	// carries enough information in that case.
	//
	// node_visible_to() filters out anything the viewer isn't entitled to.
	SearchNodes(ctx context.Context, arg SearchNodesParams) ([]SearchNodesRow, error)
	// Parent picker for the post form. type_filter restricts to a single node
	// type ('topic' when creating a view or sub-topic); leave it empty to match
	// any type ('topic', 'view', or 'finding') — used when creating a finding,
	// which can attach to any existing node. Fuzzy-searches titles when a query
	// is given; falls back to recency order when empty so the picker is
	// pre-populated. Respects node_visible_to() so viewers only see candidates
	// they can post under.
	//
	// When type_filter is empty (finding flow), candidates are bucketed by how
	// specific a parent they make: views and sub-topics first (a finding most
	// naturally attaches to a concrete stance or a narrow topic), then root
	// topics and other findings. Inside each bucket, the usual recency / fuzzy-
	// match order applies. Single-type queries skip the bucket so the original
	// order is preserved.
	SearchPostParents(ctx context.Context, arg SearchPostParentsParams) ([]SearchPostParentsRow, error)
	// Live-suggest fuzzy match against tag names, gated by visible-node count so
	// a tag that only sits on private nodes doesn't leak via the suggestion. Used
	// by the graph viewer's tag filter at /tags/suggest.
	SearchTagsForViewer(ctx context.Context, arg SearchTagsForViewerParams) ([]Tag, error)
	// People search for /search. Prefix/substring matching makes exact handle
	// discovery predictable, while trigram word similarity catches small typos.
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	// Updates a member's role. Owners are protected — their role cannot be
	// changed here; transferring ownership is a separate flow. Reports the
	// number of affected rows so callers can distinguish "no such member"
	// from "owner protected".
	SetGroupMemberRole(ctx context.Context, arg SetGroupMemberRoleParams) (int64, error)
	// Upsert: changing your stance from supports → opposes (or any other
	// transition) replaces the existing row in place. created_at is reset on
	// update so the profile shows the most recent stance change first. Returns
	// the pin's id so callers can attach findings to it.
	SetPin(ctx context.Context, arg SetPinParams) (uuid.UUID, error)
	// Marks a comment removed without deleting it. The thread keeps its shape;
	// the renderer shows "comment removed" in place of the body.
	SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) (int64, error)
	// Reverse of HighlightEdge: clears the rank on whichever side matches
	// pov_node. No-op if pov_node isn't one of the edge's endpoints.
	UnhighlightEdge(ctx context.Context, arg UnhighlightEdgeParams) (int64, error)
	// Edits a comment's body. Only the author can edit, and only while not
	// soft-deleted. updated_at bumps; the UI treats updated_at > created_at
	// as "edited".
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Node, error)
	UpdateGroupMemberVisibility(ctx context.Context, arg UpdateGroupMemberVisibilityParams) error
	// Owner-only — the handler enforces that. Stored as the same enum the
	// create form populates: 'public' | 'connections' | 'private'.
	UpdateGroupVisibility(ctx context.Context, arg UpdateGroupVisibilityParams) error
	UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error)
	UpdatePasswordIdentitySecret(ctx context.Context, arg UpdatePasswordIdentitySecretParams) error
	// Keeps the password identity's subject (an email mirror) aligned with the
	// user's current email when admins change it. Login itself looks up by
	// users.email, so the subject is essentially metadata — but we keep it in
	// sync to avoid future surprises.
	UpdatePasswordIdentitySubject(ctx context.Context, arg UpdatePasswordIdentitySubjectParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	// Updates the composer and display defaults. Timezone is an IANA name
	// (empty string = fall back to UTC).
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
	UpdateUserProfileImage(ctx context.Context, arg UpdateUserProfileImageParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) error
	// Idempotent: returns the tag id whether it already existed or just got
	// inserted. The DO UPDATE SET name=EXCLUDED.name is a no-op that exists
	// only so RETURNING fires on the conflict path.
	UpsertTag(ctx context.Context, name string) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
